### ISSUE TITLE
Fails when running with multiple Accounts unlocked

### ISSUE THREAD

**Issue by ifalatik** [KairuDeibisu/PowerToysRunPlugin1Password#2]
I have multiple accounts signed into my 1Pw application. When trying to use this plugin it fails with the following error:

```
Version: 0.78.0.0
OS Version: Microsoft Windows NT 10.0.22631.0
IntPtr Length: 8
x64: True
Date: 3/3/2024 11:51:54 AM
Exception:
System.InvalidOperationException: multiple accounts found. Use the --account flag or set the OP_ACCOUNT environment variable to select an account.
   at OnePassword.OnePasswordManager.Op(String command, IEnumerable`1 input, Boolean returnError)
   at OnePassword.OnePasswordManager.Op[TResult](String command, String input, Boolean returnError)
   at OnePassword.OnePasswordManager.SearchForItems(IVault vault, Nullable`1 includeArchive, Nullable`1 favorite, IReadOnlyCollection`1 categories, IReadOnlyCollection`1 tags)
   at Community.PowerToys.Run.Plugin._1Password.Main.ReloadData()
   at Wox.Plugin.PluginPair.Update(PowerLauncherPluginSettings setting, IPublicAPI api, Action refreshPluginsOverviewCallback)
   at PowerLauncher.SettingsReader.ReadSettings()
   at PowerLauncher.SettingsReader.<ReadSettingsOnChange>b__9_0()
   at Microsoft.PowerToys.Settings.UI.Library.Utilities.Helper.<>c__DisplayClass7_0.<GetFileWatcher>b__0(Object o, FileSystemEventArgs e)
   at System.IO.Abstractions.FileSystemWatcherBase.OnChanged(Object sender, FileSystemEventArgs args)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(ReadOnlySpan`1 buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__85_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

I'm running the latest release.

**Comment by KairuDeibisu** [comment]
Looking into the issue is easy, but a fix is going to be interesting. 

A limitation of the settings menu is that there are no dynamic updates to the settings.

In other words, I can't load in a list of available accounts.

A potential fix would be a new setting to specify the account name or ID you would like to use.

**Comment by KairuDeibisu** [comment]
@ifalatik Please try the new release. Make sure to configure the email of the account you want to use.

<img width="529" alt="image" src="https://github.com/KairuDeibisu/PowerToysRunPlugin1Password/assets/34011041/e59cc11b-19fe-4637-a419-de1fc0110758">

**Comment by ifalatik** [comment]
Thanks for the update, however both Chrome and Windows Defender are certain there's malware in the release:

![image](https://github.com/KairuDeibisu/PowerToysRunPlugin1Password/assets/63957260/365c3300-b105-4abd-95f2-44ab6be043ed)
![image](https://github.com/KairuDeibisu/PowerToysRunPlugin1Password/assets/63957260/e06be73b-9fc6-4779-9b19-6ce65c924a7b)

I can't allow a detected virus access to my passwords, I'm sure you understand :D

**Comment by KairuDeibisu** [comment]
> Author

This is a false positive. You are welcome to read the code, and build it using the current version yourself. Everything is open source and available.

You can also try version 4 to see if you get the same message. I'm not getting that message.


https://www.virustotal.com/gui/file/edaffe8ab6abbf707d97a5f0f980e4d1cff66786761be9e25916ea20bfa9a899


Here is a virus total scan of the release too. The hash of the downloaded zip on is the same as the virus totals.
